# Generated by Django 3.2.7 on 2021-09-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upcomingEvents',
            new_name='upcomingEvent',
        ),
    ]
