# Generated by Django 3.2.7 on 2021-11-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='time',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
