# Generated by Django 3.2.7 on 2021-11-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_upcomingevent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='desc',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
