# Generated by Django 3.2.7 on 2021-11-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_upcomingevent_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingevent',
            name='desc',
        ),
    ]
