# Generated by Django 3.2.7 on 2021-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_upcomingevent_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='desc',
            field=models.CharField(default=' ', max_length=700),
        ),
    ]
