# Generated by Django 3.2.7 on 2021-11-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_upcomingevent_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='desc',
            field=models.CharField(default=None, max_length=700),
            preserve_default=False,
        ),
    ]
