# Generated by Django 3.2.7 on 2021-11-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_upcomingevent_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[(0, 'Library STEM Camp @OCT 10 : 10 AM - 5 PM'), (1, 'Food Drive @JUN 9 : 5 PM - 7 PM')], default=None, max_length=100)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('v_email', models.CharField(max_length=400)),
            ],
        ),
    ]
