# Generated by Django 3.2.7 on 2021-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='event',
            field=models.CharField(choices=[('Library STEM Camp', 'Library STEM Camp @OCT 10 : 10 AM - 5 PM'), ('Food Drive', 'Food Drive @JUN 9 : 5 PM - 7 PM')], default=None, max_length=100),
        ),
    ]
