# Generated by Django 3.2.7 on 2021-11-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20211027_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='county',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
