# Generated by Django 3.2.7 on 2021-11-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_applicant_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='readCheck',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='grade',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
