# Generated by Django 3.2.7 on 2021-11-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20211118_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='county',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
